### ISSUE TITLE
Day 1 of October Leetcode challenge

### ISSUE THREAD

**Issue by shrinathjoshi** [shrinathjoshi/Leetcode-30-day-challenge#2]
Solve day 1 of October LeetCode challenge

**Comment by Shubhankar249** [comment]
I have done in C++, is that fine?

**Comment by shrinathjoshi** [comment]
yes @Shubhankar249  please go ahead and create a pull request

**Comment by Shubhankar249** [comment]
I have created a PR, but it's failing greeting test.

**Comment by Shubhankar249** [comment]
I have made a new PR which has passed the check.

**Comment by shrinathjoshi** [comment]
Thanks for your contribution @Shubhankar249
